env:
  global:
    - CONAN_REFERENCE: "VTK/7.1.0"
    - CONAN_USERNAME: "bilke"
    - CONAN_LOGIN_USERNAME: "jenkins"
    - CONAN_CHANNEL: "testing"
    - CONAN_UPLOAD: "https://ogs.jfrog.io/ogs/api/conan/conan"
    - CONAN_STABLE_BRANCH_PATTERN: "release/*"
    - CONAN_TOTAL_PAGES: 8
    - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1 # Will only upload when the branch matches "release/*"

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:

    - <<: *linux
      env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
    - <<: *linux
      env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
    - <<: *linux
      env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
    - <<: *linux
      env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.2 CONAN_DOCKER_IMAGE=lasote/conangcc52 CONAN_CURRENT_PAGE=1
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.2 CONAN_DOCKER_IMAGE=lasote/conangcc52 CONAN_CURRENT_PAGE=2
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.2 CONAN_DOCKER_IMAGE=lasote/conangcc52 CONAN_CURRENT_PAGE=3
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.2 CONAN_DOCKER_IMAGE=lasote/conangcc52 CONAN_CURRENT_PAGE=4
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.2 CONAN_DOCKER_IMAGE=lasote/conangcc52 CONAN_CURRENT_PAGE=5
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.2 CONAN_DOCKER_IMAGE=lasote/conangcc52 CONAN_CURRENT_PAGE=6
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.2 CONAN_DOCKER_IMAGE=lasote/conangcc52 CONAN_CURRENT_PAGE=7
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.2 CONAN_DOCKER_IMAGE=lasote/conangcc52 CONAN_CURRENT_PAGE=8
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.3 CONAN_DOCKER_IMAGE=lasote/conangcc53 CONAN_CURRENT_PAGE=1
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.3 CONAN_DOCKER_IMAGE=lasote/conangcc53 CONAN_CURRENT_PAGE=2
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.3 CONAN_DOCKER_IMAGE=lasote/conangcc53 CONAN_CURRENT_PAGE=3
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.3 CONAN_DOCKER_IMAGE=lasote/conangcc53 CONAN_CURRENT_PAGE=4
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.3 CONAN_DOCKER_IMAGE=lasote/conangcc53 CONAN_CURRENT_PAGE=5
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.3 CONAN_DOCKER_IMAGE=lasote/conangcc53 CONAN_CURRENT_PAGE=6
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.3 CONAN_DOCKER_IMAGE=lasote/conangcc53 CONAN_CURRENT_PAGE=7
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.3 CONAN_DOCKER_IMAGE=lasote/conangcc53 CONAN_CURRENT_PAGE=8
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.4 CONAN_DOCKER_IMAGE=lasote/conangcc54 CONAN_CURRENT_PAGE=1
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.4 CONAN_DOCKER_IMAGE=lasote/conangcc54 CONAN_CURRENT_PAGE=2
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.4 CONAN_DOCKER_IMAGE=lasote/conangcc54 CONAN_CURRENT_PAGE=3
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.4 CONAN_DOCKER_IMAGE=lasote/conangcc54 CONAN_CURRENT_PAGE=4
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.4 CONAN_DOCKER_IMAGE=lasote/conangcc54 CONAN_CURRENT_PAGE=5
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.4 CONAN_DOCKER_IMAGE=lasote/conangcc54 CONAN_CURRENT_PAGE=6
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.4 CONAN_DOCKER_IMAGE=lasote/conangcc54 CONAN_CURRENT_PAGE=7
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5.4 CONAN_DOCKER_IMAGE=lasote/conangcc54 CONAN_CURRENT_PAGE=8
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6.2 CONAN_DOCKER_IMAGE=lasote/conangcc62 CONAN_CURRENT_PAGE=1
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6.2 CONAN_DOCKER_IMAGE=lasote/conangcc62 CONAN_CURRENT_PAGE=2
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6.2 CONAN_DOCKER_IMAGE=lasote/conangcc62 CONAN_CURRENT_PAGE=3
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6.2 CONAN_DOCKER_IMAGE=lasote/conangcc62 CONAN_CURRENT_PAGE=4
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6.2 CONAN_DOCKER_IMAGE=lasote/conangcc62 CONAN_CURRENT_PAGE=5
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6.2 CONAN_DOCKER_IMAGE=lasote/conangcc62 CONAN_CURRENT_PAGE=6
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6.2 CONAN_DOCKER_IMAGE=lasote/conangcc62 CONAN_CURRENT_PAGE=7
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6.2 CONAN_DOCKER_IMAGE=lasote/conangcc62 CONAN_CURRENT_PAGE=8
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6.3 CONAN_DOCKER_IMAGE=lasote/conangcc63 CONAN_CURRENT_PAGE=1
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6.3 CONAN_DOCKER_IMAGE=lasote/conangcc63 CONAN_CURRENT_PAGE=2
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6.3 CONAN_DOCKER_IMAGE=lasote/conangcc63 CONAN_CURRENT_PAGE=3
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6.3 CONAN_DOCKER_IMAGE=lasote/conangcc63 CONAN_CURRENT_PAGE=4
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6.3 CONAN_DOCKER_IMAGE=lasote/conangcc63 CONAN_CURRENT_PAGE=5
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6.3 CONAN_DOCKER_IMAGE=lasote/conangcc63 CONAN_CURRENT_PAGE=6
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6.3 CONAN_DOCKER_IMAGE=lasote/conangcc63 CONAN_CURRENT_PAGE=7
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6.3 CONAN_DOCKER_IMAGE=lasote/conangcc63 CONAN_CURRENT_PAGE=8
    - <<: *linux
      env: CONAN_GCC_VERSIONS=7.1 CONAN_DOCKER_IMAGE=lasote/conangcc71 CONAN_CURRENT_PAGE=1
    - <<: *linux
      env: CONAN_GCC_VERSIONS=7.1 CONAN_DOCKER_IMAGE=lasote/conangcc71 CONAN_CURRENT_PAGE=2
    - <<: *linux
      env: CONAN_GCC_VERSIONS=7.1 CONAN_DOCKER_IMAGE=lasote/conangcc71 CONAN_CURRENT_PAGE=3
    - <<: *linux
      env: CONAN_GCC_VERSIONS=7.1 CONAN_DOCKER_IMAGE=lasote/conangcc71 CONAN_CURRENT_PAGE=4
    - <<: *linux
      env: CONAN_GCC_VERSIONS=7.1 CONAN_DOCKER_IMAGE=lasote/conangcc71 CONAN_CURRENT_PAGE=5
    - <<: *linux
      env: CONAN_GCC_VERSIONS=7.1 CONAN_DOCKER_IMAGE=lasote/conangcc71 CONAN_CURRENT_PAGE=6
    - <<: *linux
      env: CONAN_GCC_VERSIONS=7.1 CONAN_DOCKER_IMAGE=lasote/conangcc71 CONAN_CURRENT_PAGE=7
    - <<: *linux
      env: CONAN_GCC_VERSIONS=7.1 CONAN_DOCKER_IMAGE=lasote/conangcc71 CONAN_CURRENT_PAGE=8
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE=1
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE=2
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE=3
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE=4
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE=5
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE=6
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE=7
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE=8
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE=1
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE=2
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE=3
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE=4
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE=5
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE=6
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE=7
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE=8
    - <<: *osx
      osx_image: xcode7.0
      env: CONAN_APPLE_CLANG_VERSIONS=7.0 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
    - <<: *osx
      osx_image: xcode7.0
      env: CONAN_APPLE_CLANG_VERSIONS=7.0 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
    - <<: *osx
      osx_image: xcode7.0
      env: CONAN_APPLE_CLANG_VERSIONS=7.0 CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
    - <<: *osx
      osx_image: xcode7.0
      env: CONAN_APPLE_CLANG_VERSIONS=7.0 CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
    - <<: *osx
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
    - <<: *osx
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
    - <<: *osx
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
    - <<: *osx
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
    - <<: *osx
      osx_image: xcode8.2
      env: CONAN_APPLE_CLANG_VERSIONS=8.0 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
    - <<: *osx
      osx_image: xcode8.2
      env: CONAN_APPLE_CLANG_VERSIONS=8.0 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
    - <<: *osx
      osx_image: xcode8.2
      env: CONAN_APPLE_CLANG_VERSIONS=8.0 CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
    - <<: *osx
      osx_image: xcode8.2
      env: CONAN_APPLE_CLANG_VERSIONS=8.0 CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
    - <<: *osx
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
    - <<: *osx
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
    - <<: *osx
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
    - <<: *osx
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
