build: false
environment:
  PYTHON: "C:\\Python27-x64"
  PYTHON_VERSION: "2.7.11"
  PYTHON_ARCH: "64"

  CONAN_REFERENCE: "VTK/7.1.0"
  CONAN_USERNAME: "bilke"
  CONAN_LOGIN_USERNAME: "bilke"
  CONAN_CHANNEL: "testing"
  CONAN_STABLE_BRANCH_PATTERN: "release/*"
  VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
  CONAN_TOTAL_PAGES: 4
  CONAN_UPLOAD: "https://api.bintray.com/conan/ogs/conan"

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 12
      CONAN_CURRENT_PAGE: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 12
      CONAN_CURRENT_PAGE: 2
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 12
      CONAN_CURRENT_PAGE: 3
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 12
      CONAN_CURRENT_PAGE: 4

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_CURRENT_PAGE: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_CURRENT_PAGE: 2
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_CURRENT_PAGE: 3
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_CURRENT_PAGE:

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_CURRENT_PAGE: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_CURRENT_PAGE: 2
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_CURRENT_PAGE: 3
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_CURRENT_PAGE: 4

install:
    - set PATH=%PYTHON%/Scripts/;%PATH%
    - pip.exe install conan --upgrade
    - pip.exe install conan_package_tools --upgrade
    - conan user # It creates the conan data directory

test_script:
  - C:\Python27-x64\python build.py
